In [17]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [18]:
df=pd.read_csv("Dataset.csv")

In [3]:
df

Country   Age  Salary  Purchased
0    India    38   68000         No
1   France    43   45000        Yes
2  Germany    30   54000         No
3   France    48   65000         No
4  Germany    40     nan        Yes
5   France    35   58000        Yes
6  Germany   nan   53000         No
7   France    49   79000        Yes
8    India    50   88000         No
9   France    37   77000        Yes

In [4]:
x= df.iloc[:,:-1].values

In [5]:
print(x)

[['India' ' 38' ' 68000']
 ['France' ' 43' ' 45000']
 ['Germany' ' 30' ' 54000']
 ['France' ' 48' ' 65000']
 ['Germany' ' 40' ' nan']
 ['France' ' 35' ' 58000']
 ['Germany' ' nan' ' 53000']
 ['France' ' 49' ' 79000']
 ['India' ' 50' ' 88000']
 ['France' ' 37' ' 77000']]


In [6]:
y= df.iloc[:,3].values

In [7]:
print(y)

[' No' ' Yes' ' No' ' No' ' Yes' ' Yes' ' No' ' Yes' ' No' ' Yes']


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy ='mean')

In [10]:
imputer = imputer.fit(x[:, 1:3])

x[:, 1:3] = imputer.transform(x[:, 1:3])

In [11]:
print(x)

[['India' 38.0 68000.0]
 ['France' 43.0 45000.0]
 ['Germany' 30.0 54000.0]
 ['France' 48.0 65000.0]
 ['Germany' 40.0 65222.22222222222]
 ['France' 35.0 58000.0]
 ['Germany' 41.111111111111114 53000.0]
 ['France' 49.0 79000.0]
 ['India' 50.0 88000.0]
 ['France' 37.0 77000.0]]


In [21]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
x[:, 0]= labelencoder.fit_transform(x[:,0])

In [22]:
print(x)

[[2 38.0 68000.0]
 [0 43.0 45000.0]
 [1 30.0 54000.0]
 [0 48.0 65000.0]
 [1 40.0 65222.22222222222]
 [0 35.0 58000.0]
 [1 41.111111111111114 53000.0]
 [0 49.0 79000.0]
 [2 50.0 88000.0]
 [0 37.0 77000.0]]


In [24]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
x= enc.fit_transform(x).toarray()

In [25]:
print(x)

[[0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

In [27]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=0)

In [29]:
from sklearn import preprocessing
st_x = preprocessing.StandardScaler().fit(x_train)

In [30]:
st_x

StandardScaler()

In [31]:
st_x.mean_

array([0.625, 0.25 , 0.125, 0.   , 0.125, 0.125, 0.125, 0.125, 0.125,
       0.125, 0.125, 0.125, 0.   , 0.125, 0.125, 0.   , 0.125, 0.125,
       0.125, 0.125, 0.125, 0.125, 0.   ])

In [33]:
st_x.scale_

array([0.48412292, 0.4330127 , 0.33071891, 1.        , 0.33071891,
       0.33071891, 0.33071891, 0.33071891, 0.33071891, 0.33071891,
       0.33071891, 0.33071891, 1.        , 0.33071891, 0.33071891,
       1.        , 0.33071891, 0.33071891, 0.33071891, 0.33071891,
       0.33071891, 0.33071891, 1.        ])

In [34]:
x_scaled = st_x.transform(x_train)

In [35]:
x_scaled

array([[-1.29099445,  1.73205081, -0.37796447,  0.        , -0.37796447,
        -0.37796447, -0.37796447,  2.64575131, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447,  0.        , -0.37796447, -0.37796447,
         0.        , -0.37796447, -0.37796447,  2.64575131, -0.37796447,
        -0.37796447, -0.37796447,  0.        ],
       [ 0.77459667, -0.57735027, -0.37796447,  0.        , -0.37796447,
         2.64575131, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447,  0.        , -0.37796447, -0.37796447,
         0.        , -0.37796447, -0.37796447, -0.37796447, -0.37796447,
         2.64575131, -0.37796447,  0.        ],
       [ 0.77459667, -0.57735027, -0.37796447,  0.        , -0.37796447,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447,  2.64575131,
        -0.37796447, -0.37796447,  0.        ,  2.64575131, -0.37796447,
         0.        , -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.3779

In [36]:
x_scaled.mean(axis=0)

array([ 2.77555756e-17, -2.77555756e-17, -4.16333634e-17,  0.00000000e+00,
       -5.55111512e-17, -6.93889390e-17, -4.16333634e-17, -6.93889390e-17,
       -1.38777878e-17, -1.38777878e-17, -2.77555756e-17, -1.38777878e-17,
        0.00000000e+00, -1.38777878e-17, -1.38777878e-17,  0.00000000e+00,
       -5.55111512e-17, -2.77555756e-17, -6.93889390e-17, -4.16333634e-17,
       -6.93889390e-17, -1.38777878e-17,  0.00000000e+00])

In [37]:
x_scaled.std(axis=0)

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 0.])

In [38]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [41]:
x, y = make_classification(random_state=42)
x_train, x_test, y_train, y_test= train_test_split(x, y, random_state=42)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(x_train, y_train)
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',LogisticRegression())])

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [42]:
pipe.score(x_test, y_test)

0.96